---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-elixir-app
  namespace: default
  labels:
    app.kubernetes.io/name: my-elixir-app
    app.kubernetes.io/instance: myapp-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: my-elixir-app
      app.kubernetes.io/instance: myapp-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-elixir-app
        app.kubernetes.io/instance: myapp-node
    spec:
      containers:
        - name: main
          image: pss-image:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RELEASE_NODE_IP
              value: 127.0.0.1
            - name: RELEASE_COOKIE
              value: cookie
          ports:
            - name: epmd
              containerPort: 4369
              protocol: TCP