apiVersion: v1
kind: Service
metadata:
  name: my-elixir-app-service
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: my-elixir-app
    app.kubernetes.io/instance: myapp-node
  ports:
    - name: http
      port: 80
      targetPort: 4369